export enum AuditAction {
  // ========== Autenticación ==========
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAILED = "LOGIN_FAILED",
  LOGOUT = "LOGOUT",
  AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN",
  AUTH_USER_REJECTED = "AUTH_USER_REJECTED",

  // ========== Check-in ==========
  CHECKIN_SUCCESS = "CHECKIN_SUCCESS",
  CHECKIN_FAILED = "CHECKIN_FAILED",

  // ========== Usuarios ==========
  USER_CREATED = "USER_CREATED",
  USER_UPDATED = "USER_UPDATED",

  // ========== Eventos ==========
  EVENT_CREATED = "EVENT_CREATED",
  EVENT_UPDATED = "EVENT_UPDATED",
  EVENT_DELETED = "EVENT_DELETED",
  EVENT_MARKED_OVERLAP = "EVENT_MARKED_OVERLAP",
  CHECKIN_EXPIRED = "CHECKIN_EXPIRED",

  // ========== Salas ==========
  ROOM_ADDED = "ROOM_ADDED",
  ROOM_DELETED = "ROOM_DELETED",
  ROOM_RESTORED = "ROOM_RESTORED",
  ROOM_BUSY = "ROOM_BUSY",
  ROOM_AVAILABLE = "ROOM_AVAILABLE",
}
